AWSTemplateFormatVersion: '2010-09-09-OC'
Description: default template generated for organization with master account 438902864846

Definitions:
  - &defaultAccountTags
      department: Platform
      project: Infrastructure
      budget-alarm-threshold: 10
      cloudwatch-cloudTrail-log-retention-period: 90

Organization:
##############################
# OU'S
##############################

  OrganizationRoot:
    Type: OC::ORG::OrganizationRoot
    Properties:
      DefaultOrganizationAccessRoleName: OrganizationAccountAccessRole

  # Organizational Unit used for dev and testing workloads
  DevOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: dev
      Accounts:
        - !Ref DevelopmentAccount

  # Organizational Unit used for Production workloads
  ProdOu:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: prod
      Accounts: 
        - !Ref ProductionAccount

  # Organizational Unit used for shared infrastructure services
  SharedOu:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: shared
      Accounts:
        - !Ref AuditAccount

  # Organizational Unit that contains accounts to be deleted from organization
  SuspendedOu:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: suspended
      Accounts: []


##############################
# ACCOUNTS
##############################
  ManagementAccount:
    Type: OC::ORG::MasterAccount
    Properties:
      Alias: hyperbase-management
      AccountName: Hyperbase Management
      AccountId: '438902864846'
      RootEmail: mkoelle+aws-hyperbase@gmail.com
      Tags:
        <<: *defaultAccountTags

  ProductionAccount:
    Type: OC::ORG::Account
    Properties:
      Alias: hyperbase-prod
      AccountName: Hyperbase Production
      RootEmail: mkoelle+hyperbase-prod@gmail.com
      Tags:
        <<: *defaultAccountTags
        account-owner-email: mkoelle+aws-hyperbase@gmail.com

  DevelopmentAccount:
    Type: OC::ORG::Account
    Properties:
      Alias: hyperbase-dev
      AccountName: Hyperbase Development
      RootEmail: mkoelle+hyperbase-dev@gmail.com
      Tags:
        <<: *defaultAccountTags
        account-owner-email: mkoelle+aws-hyperbase@gmail.com

  AuditAccount:
    Type: OC::ORG::Account
    Properties:
      Alias: hyperbase-audit
      AccountName: Hyperbase Audit
      RootEmail: mkoelle+hyperbase-audit@gmail.com
      Tags:
        <<: *defaultAccountTags
        account-owner-email: mkoelle+aws-hyperbase@gmail.com
