AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates a route53 Hosted Zone with a child shadow zone'
Parameters:
  Domain:
    Type: 'String'
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: must be a valid DNS name.
  LogGroupArn:
    Type: 'String'
    ConstraintDescription: must be a valid log group Arn.
Resources:
  RootZone:
    Type: 'AWS::Route53::HostedZone'
    Properties:
      Name: !Ref Domain
      HostedZoneConfig:
        Comment: 'parent hosted zone'
      QueryLoggingConfig:
        CloudWatchLogsLogGroupArn: !Ref LogGroupArn
  ShadowZone:
    Type: 'AWS::Route53::HostedZone'
    Properties:
      Name: !Sub 'shadow.${Domain}'
      HostedZoneConfig:
        Comment: 'playground hosted zone for testing'
      QueryLoggingConfig:
        CloudWatchLogsLogGroupArn: !Ref LogGroupArn
  ShadowRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref RootZone
      Name: !Sub 'shadow.${Domain}'
      Type: 'NS'
      TTL: 900
      ResourceRecords: !GetAtt ShadowZone.NameServers
Outputs:
  RootZone:
    Value: !Ref Domain
  RootZoneId:
    Value: !Ref RootZone
    Export:
      Name: 
        !Join [ '-', [ !Join [ '-', !Split ['.', !Ref Domain ] ], 'id' ] ]
  RootZoneNameServers:
    Value: !Join [ ';', !GetAtt RootZone.NameServers ]
    Export:
      Name: 
        !Join [ '-', [ !Join [ '-', !Split ['.', !Ref Domain ] ], 'nameservers' ] ]
  ShadowZone:
    Value: !Sub 'shadow.${Domain}'
  ShadowZoneId:
    Value: !Ref ShadowZone
    Export:
      Name: 
        !Join [ '-', [ !Join [ '-', !Split ['.', !Sub 'shadow.${Domain}' ] ], 'id' ] ]
  ShadowZoneNameServers:
    Value: !Join [ ';', !GetAtt ShadowZone.NameServers ]
    Export:
      Name: 
        !Join [ '-', [ !Join [ '-', !Split ['.', !Sub 'shadow.${Domain}' ] ], 'nameservers' ] ]
