AWSTemplateFormatVersion: '2010-09-09-OC'

# Include file that contains Organization Section.
# The Organization Section describes Accounts, Organizational Units, etc.
Organization: !Include ../../organization.yml

# Any Binding that does not explicitly specify a region will default to this.
# Value can be either string or list
DefaultOrganizationBindingRegion: us-east-1

Resources:
  DeploymentUser:
    Type: AWS::IAM::User
    OrganizationBinding: !Ref AllBinding
    Properties:
      UserName: AutomatedDeployer
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      
  ProjectDeveloperBoundary:
    Type: AWS::IAM::ManagedPolicy
    OrganizationBinding: !Ref AllBinding
    Properties:
      ManagedPolicyName: AllActionsSameProject
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Deny"
            Action:
              - '*'
            Resource: '*'
            Condition:
              StringNotEqualsIfExists:
                "aws:ResourceTag/Project": "${aws:PrincipalTag/Project}"
