AWSTemplateFormatVersion: '2010-09-09-OC'

# Include file that contains Organization Section.
# The Organization Section describes Accounts, Organizational Units, etc.
Organization: !Include ../../organization.yml

# Any Binding that does not explicitly specify a region will default to this.
# Value can be either string or list
DefaultOrganizationBindingRegion: us-east-1

Parameters:

  resourcePrefix:
    Type: String

  rootHostedZoneName:
    Type: String

# Section contains a named set of Bindings.
# Bindings determine what resources are deployed where
# These bindings can be !Ref'd from the Resources in the resource section
OrganizationBindings:

  # binding for HostedZone, HostedZoneIdParam, HostedZoneNameParam
  HostedZoneBinding:
    Account: !Ref DevelopmentAccount

  # binding for RootHostedZone, ParentNsRecord
  RootHostedZoneBinding:
    Account: !Ref ProductionAccount

Resources:

  #=========================================#
  # Zone
  #=========================================#

  HostedZone:
    Type: AWS::Route53::HostedZone
    OrganizationBinding: !Ref HostedZoneBinding
    Properties:
      HostedZoneConfig:
        Comment: Domain Hosted Zone
      Name: !Sub 'shadow.${rootHostedZoneName}.'

  HostedZoneIdParam:
    Type: AWS::SSM::Parameter
    OrganizationBinding: !Ref HostedZoneBinding
    Properties:
      Name: !Sub '${resourcePrefix}-domains-hosted-zone-id'
      Type: String
      Value: !GetAtt AWSAccount.Resources.HostedZone

  HostedZoneNameParam:
    Type: AWS::SSM::Parameter
    OrganizationBinding: !Ref HostedZoneBinding
    Properties:
      Name: !Sub '${resourcePrefix}-domains-hosted-zone-name'
      Type: String
      Value: !Sub 'shadow.${rootHostedZoneName}.'

  #=========================================#
  # Parent Record
  #=========================================#

  RootHostedZone:
    Type: AWS::Route53::HostedZone
    OrganizationBinding: !Ref RootHostedZoneBinding
    Properties:
      HostedZoneConfig:
        Comment: Root domain
      Name: !Ref rootHostedZoneName

  # be aware that changing the logicalName for a AWS::Route53::RecordSet resource
  # might result in the Record being deleted. this unfortunately seems to be a cloudformation issue
  # described here: https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/364
  # workaround is to remove the resource and then add it.
  ParentNsRecord:
    DependsOn: RootHostedZone
    Type: AWS::Route53::RecordSet
    OrganizationBinding: !Ref RootHostedZoneBinding
    ForeachAccount: !Ref HostedZoneBinding
    Properties:
      Type: NS
      HostedZoneName: !Sub '${rootHostedZoneName}.'
      Name: !Sub 'shadow.${rootHostedZoneName}.'
      TTL: 86400
      ResourceRecords: !GetAtt CurrentAccount.Resources.HostedZone.NameServers

